# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-31 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20171212_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeseriesResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('time_period', models.CharField(choices=[('current', 'Current'), ('1d', 'One Day'), ('5d', 'Five Days'), ('1m', 'One Month'), ('3m', 'Three Months'), ('1y', 'One Year'), ('max', 'Max Time Period')], max_length=2)),
                ('result', jsonfield.fields.JSONField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='timeseriesresult',
            unique_together=set([('stock', 'time_period')]),
        ),
    ]
