# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_company_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='daily_diff',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='daily_diff_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='open',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.BigIntegerField(default=0),
        ),
    ]
