# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20171212_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='previous_close',
            field=models.FloatField(default=0.0),
        ),
    ]
