# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stock_previous_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='daily_diff',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='daily_diff_percent',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='previous_close',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
