# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20171231_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriesresult',
            name='time_period',
            field=models.CharField(choices=[('current', 'Current'), ('1d', 'One Day'), ('5d', 'Five Days'), ('1m', 'One Month'), ('3m', 'Three Months'), ('1y', 'One Year'), ('max', 'Max Time Period')], max_length=7),
        ),
    ]
